name: DEV-CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    #    This job will build the dist folder to be deployed
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build -- --prod

